# Configuration for Travis CI
# When making changes, make sure to also edit tox.ini file.

language: python

python:
  - "2.6"
  - "2.7"
  - "3.6"

install: "pip install . --use-mirrors"

script: python setup.py nosetests

notifications:
  email:
    recipients:
      - travisci@aweber.com
